import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const CARD_DIR = path.join(ROOT, "data", "culture_cards");
const STAGE0_FILE = path.join(CARD_DIR, "r24_stage0_concept_closure.jsonl");
const STAGE1A_FILE = path.join(CARD_DIR, "r24_stage1a_closure_pack.jsonl");

const OUTPUT_NAMES = new Set([
  path.basename(STAGE0_FILE),
  path.basename(STAGE1A_FILE)
]);

const CONVERSATION_MOVES = {
  overview: "definition_unit",
  works_list: "list_items_or_none",
  representative_works: "representative_items",
  entry_path: "guided_sequence",
  explain_work: "summary_no_quotes",
  compare: "contrast_axes",
  country_relation: "country_language_institution_split",
  why_it_matters: "field_effect",
  quote_or_lyrics_boundary: "no_long_quotes"
};

const COPYRIGHT_POLICY = "Use titles, metadata, themes, and short paraphrase only; no lyrics or long copyrighted excerpts.";

function readJsonl(file) {
  if (!fs.existsSync(file)) return [];
  return fs.readFileSync(file, "utf8")
    .split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line));
}

function existingIds() {
  const ids = new Set();
  for (const name of fs.readdirSync(CARD_DIR).filter((file) => file.endsWith(".jsonl"))) {
    if (OUTPUT_NAMES.has(name)) continue;
    for (const row of readJsonl(path.join(CARD_DIR, name))) ids.add(row.id);
  }
  return ids;
}

function baseCard({
  id,
  entity_type,
  names,
  domain,
  factual_core,
  themes = [],
  related_entities = [],
  comparison_axes = [],
  entry_points = ["definition_unit", "contrast_unit"],
  works = [],
  representative_works = [],
  periods = [],
  style_axes = [],
  historical_context = [],
  source_summary = "R24 public source-backed cultural card; compact metadata only.",
  confidence = 0.82,
  eval_tags = []
}) {
  return {
    id,
    entity_type,
    names,
    domain,
    factual_core,
    short_intro: factual_core,
    works,
    representative_works,
    periods,
    themes,
    style_axes,
    historical_context,
    entry_points,
    related_entities,
    comparison_axes,
    conversation_moves: { ...CONVERSATION_MOVES },
    safe_boundaries: [
      "no long quotations",
      "no lyrics",
      "do not infer private intention",
      "mark uncertainty when scope is partial"
    ],
    copyright_policy: COPYRIGHT_POLICY,
    followup_bindings: [],
    source_summary,
    confidence,
    visibility: "public",
    approved_for_public_runtime: true,
    not_to_infer: [
      "complete canon",
      "private motive",
      "direct influence without evidence",
      "identity equivalence from loose analogy"
    ],
    needs_review: false,
    eval_tags
  };
}

function conceptCard({
  id,
  names,
  domain,
  factual_core,
  definition_units,
  examples = [],
  non_examples = [],
  related_concepts = [],
  related_people = [],
  relation_ids = [],
  common_misreadings = [],
  negative_moves = [],
  boundary_notes = [],
  provenance = [],
  transfer_scope = [],
  themes = [],
  comparison_axes = [],
  entity_type
}) {
  const card = baseCard({
    id,
    entity_type: entity_type || (id.startsWith("theme.") ? "theme" : "concept"),
    names,
    domain,
    factual_core,
    themes: [...new Set([...themes, ...related_concepts])],
    related_entities: [
      ...related_concepts.map((concept) => ({ id: concept, relation: "related_concept" })),
      ...related_people.map((person) => ({ id: person, relation: "related_person" })),
      ...relation_ids.map((relation) => ({ id: relation, relation: "relation_card" }))
    ],
    comparison_axes,
    eval_tags: ["r24", "concept"]
  });
  return {
    ...card,
    definition_units,
    examples,
    non_examples,
    related_concepts,
    related_people,
    relation_ids,
    common_misreadings,
    negative_moves,
    boundary_notes,
    provenance,
    transfer_scope,
    turn_functions: [
      "define_concept",
      "explain_relation",
      "compare_forms",
      "topic_reentry",
      "meaningful_non_question"
    ]
  };
}

function personCard({
  id,
  names,
  domain,
  roles,
  period,
  regions_languages,
  representative_works,
  themes,
  style_axes,
  related_concepts = [],
  related_people = [],
  negative_moves = [],
  uncertainty_notes = [],
  provenance = [],
  transfer_scope = []
}) {
  const card = baseCard({
    id,
    entity_type: "person",
    names,
    domain,
    factual_core: `${names[0]}: ${roles.join(", ")}; period=${period}.`,
    works: representative_works,
    representative_works,
    periods: [period],
    themes,
    style_axes,
    related_entities: [
      ...representative_works.map((work) => ({ id: work, relation: "representative_work" })),
      ...related_concepts.map((concept) => ({ id: concept, relation: "related_concept" })),
      ...related_people.map((person) => ({ id: person, relation: "contrast_or_neighbor" }))
    ],
    comparison_axes: style_axes,
    eval_tags: ["r24", "person"]
  });
  return {
    ...card,
    roles,
    period,
    regions_languages,
    related_concepts,
    related_people,
    negative_moves,
    uncertainty_notes,
    provenance,
    transfer_scope,
    turn_functions: [
      "identify_person",
      "list_representative_works",
      "explain_characteristics",
      "compare_people",
      "topic_reentry"
    ]
  };
}

function workCard({
  id,
  names,
  domain,
  creator_ids,
  work_type,
  period,
  factual_core,
  themes,
  style_axes = [],
  related_concepts = [],
  related_people = [],
  examples = [],
  negative_moves = [],
  boundary_notes = [],
  provenance = [],
  transfer_scope = []
}) {
  const card = baseCard({
    id,
    entity_type: "work",
    names,
    domain,
    factual_core,
    themes,
    style_axes,
    periods: [period],
    related_entities: [
      ...creator_ids.map((creator) => ({ id: creator, relation: "creator_or_primary_context" })),
      ...related_concepts.map((concept) => ({ id: concept, relation: "related_concept" })),
      ...related_people.map((person) => ({ id: person, relation: "related_person" }))
    ],
    comparison_axes: style_axes,
    eval_tags: ["r24", "work"]
  });
  return {
    ...card,
    creator_ids,
    work_type,
    related_concepts,
    related_people,
    examples,
    negative_moves,
    boundary_notes,
    copyright_boundary: "summary_paraphrase_only",
    provenance,
    transfer_scope,
    turn_functions: [
      "list_representative_works",
      "explain_characteristics",
      "compare_works",
      "concept_followup",
      "recommend_items"
    ]
  };
}

function relationCard({
  id,
  names,
  domain,
  relation_type,
  source_ids,
  target_ids,
  shared_axes = [],
  contrast_axes = [],
  licensed_verbs = [],
  example_ids = [],
  constraints = [],
  negative_moves = [],
  provenance = [],
  transfer_scope = []
}) {
  const card = baseCard({
    id,
    entity_type: "relation",
    names,
    domain,
    factual_core: `${relation_type}: ${source_ids.join("+")} -> ${target_ids.join("+")}.`,
    themes: shared_axes,
    related_entities: [
      ...source_ids.map((source) => ({ id: source, relation: "source" })),
      ...target_ids.map((target) => ({ id: target, relation: "target" })),
      ...example_ids.map((example) => ({ id: example, relation: "example" }))
    ],
    comparison_axes: [...shared_axes, ...contrast_axes],
    eval_tags: ["r24", "relation"]
  });
  return {
    ...card,
    relation_type,
    source_ids,
    target_ids,
    shared_axes,
    contrast_axes,
    licensed_verbs,
    example_ids,
    constraints,
    negative_moves,
    provenance,
    transfer_scope,
    turn_functions: [
      "explain_relation",
      "compare_forms",
      "topic_reentry",
      "cross_domain_analogy"
    ]
  };
}

const P = {
  brit: (slug) => ({ label: `Britannica:${slug}`, url: `https://www.britannica.com/${slug}` }),
  sep: (slug) => ({ label: `SEP:${slug}`, url: `https://plato.stanford.edu/entries/${slug}/` }),
  criterion: (slug) => ({ label: `Criterion:${slug}`, url: `https://www.criterion.com/${slug}` }),
  bfi: (slug) => ({ label: `BFI:${slug}`, url: `https://www.bfi.org.uk/${slug}` }),
  moma: (slug) => ({ label: `MoMA:${slug}`, url: `https://www.moma.org/${slug}` }),
  official: (label, url) => ({ label, url })
};

const stage0 = [
  conceptCard({
    id: "concept.wabi_sabi",
    names: ["侘寂", "wabi-sabi"],
    domain: "art_history",
    factual_core: "Japanese aesthetic concept linking impermanence, irregularity, patina, and restraint.",
    definition_units: ["impermanence", "irregularity", "weathering", "restraint"],
    examples: ["tea bowl surface", "aged material", "quiet asymmetry"],
    non_examples: ["pure minimalism", "luxury polish"],
    related_concepts: ["concept.mono_no_aware", "movement.minimalism", "concept.mujo_impermanence"],
    common_misreadings: ["same_as_minimalism", "same_as_mono_no_aware"],
    negative_moves: ["do_not_treat_as_generic_sadness", "do_not_treat_as_empty_style"],
    boundary_notes: ["Use as aesthetic relation, not as universal Japanese identity claim."],
    provenance: [P.official("Japan House London:wabi-sabi", "https://www.japanhouselondon.uk/discover/what-is-wabi-sabi/")],
    transfer_scope: ["design_materials", "photography_surface", "literary_mood"]
  }),
  conceptCard({
    id: "theme.boundary",
    names: ["边界", "boundary"],
    domain: "culture_boundary",
    factual_core: "Cross-domain limit marker for safety, genre, evidence, law, care, identity, and copyright.",
    definition_units: ["limit", "scope", "responsibility"],
    examples: ["copyright boundary", "care boundary", "identity boundary"],
    non_examples: ["generic refusal", "avoidance without reason"],
    related_concepts: ["theme.copyright_boundary", "theme.interpretation"],
    common_misreadings: ["boundary_equals_refusal"],
    negative_moves: ["do_not_use_as_default_escape", "do_not_weaken_required_answer"],
    boundary_notes: ["Boundary cards constrain output; they do not replace the requested operation."],
    provenance: [P.official("U.S. Copyright Office:copyright basics", "https://www.copyright.gov/circs/circ01.pdf")],
    transfer_scope: ["copyright", "identity", "care", "legal_information"]
  }),
  conceptCard({
    id: "theme.copyright_boundary",
    names: ["版权边界", "copyright boundary"],
    domain: "copyright_boundary",
    factual_core: "Limit for songs, poems, novels, films, and theory texts: metadata and paraphrase are safer than long excerpts.",
    definition_units: ["metadata", "summary", "paraphrase", "excerpt_limit"],
    examples: ["title", "creator", "theme summary"],
    non_examples: ["lyrics block", "long copyrighted passage"],
    related_concepts: ["theme.boundary"],
    common_misreadings: ["summary_requires_quotation"],
    negative_moves: ["do_not_store_lyrics", "do_not_emit_long_excerpts"],
    boundary_notes: ["When uncertain, prefer paraphrase and source-independent commentary."],
    provenance: [P.official("U.S. Copyright Office:fair use", "https://www.copyright.gov/fair-use/")],
    transfer_scope: ["music", "literature", "film", "theory"]
  }),
  conceptCard({
    id: "theme.forgetting",
    names: ["遗忘", "forgetting"],
    domain: "philosophy",
    factual_core: "Memory-related concept covering loss, selection, repression, and narrative omission.",
    definition_units: ["loss", "selection", "omission"],
    examples: ["narrative gap", "public amnesia"],
    non_examples: ["simple ignorance", "data deletion only"],
    related_concepts: ["theme.memory", "concept.narrative_memory"],
    common_misreadings: ["forgetting_equals_absence"],
    negative_moves: ["do_not_psychologize_user", "do_not_infer_trauma"],
    boundary_notes: ["Use lightly in personal turns; avoid diagnosis."],
    provenance: [P.sep("memory")],
    transfer_scope: ["literature", "history", "photography"]
  }),
  conceptCard({
    id: "theme.framing",
    names: ["框取", "构图框定", "framing"],
    domain: "photography_history",
    factual_core: "Visual and narrative selection of what is included, excluded, centered, or implied.",
    definition_units: ["selection", "exclusion", "viewpoint", "composition"],
    examples: ["film shot boundary", "photographic frame", "narrative viewpoint"],
    non_examples: ["physical border only"],
    related_concepts: ["theme.looking", "concept.narrator_point_of_view"],
    common_misreadings: ["framing_equals_border"],
    negative_moves: ["do_not_reduce_to_decoration", "do_not_ignore_exclusion"],
    boundary_notes: ["Useful across image, film, photography, and point-of-view questions."],
    provenance: [P.official("MoMA:photography", "https://www.moma.org/collection/terms/photography")],
    transfer_scope: ["film", "photography", "literature", "design"]
  }),
  conceptCard({
    id: "theme.freedom_responsibility",
    names: ["自由与责任", "freedom and responsibility"],
    domain: "philosophy",
    factual_core: "Ethical-existential pair linking choice, agency, consequence, and accountability.",
    definition_units: ["choice", "agency", "consequence", "accountability"],
    examples: ["existential choice", "ethical responsibility"],
    non_examples: ["license without consequence"],
    related_concepts: ["concept.existentialism", "concept.authenticity"],
    common_misreadings: ["freedom_equals_impulse"],
    negative_moves: ["do_not_turn_into_moralizing", "do_not_infer_private_guilt"],
    boundary_notes: ["Use for philosophical framing, not personal diagnosis."],
    provenance: [P.sep("existentialism")],
    transfer_scope: ["philosophy", "literature", "film"]
  }),
  conceptCard({
    id: "theme.institution",
    names: ["制度", "机构", "institution"],
    domain: "art_history",
    factual_core: "Social or organizational frame that shapes authority, recognition, and rule application.",
    definition_units: ["authority", "recognition", "rules", "practice"],
    examples: ["museum", "academy", "court", "school"],
    non_examples: ["individual taste only"],
    related_concepts: ["concept.authorship", "concept.rule_application_precedent"],
    common_misreadings: ["institution_equals_building_only"],
    negative_moves: ["do_not_claim_institution_explains_all"],
    boundary_notes: ["Differentiate art institutions, legal institutions, and education institutions."],
    provenance: [P.moma("collection/terms/conceptual-art")],
    transfer_scope: ["art", "law_boundary", "education", "design"]
  }),
  conceptCard({
    id: "theme.interpretation",
    names: ["解释", "阐释", "interpretation"],
    domain: "philosophy",
    factual_core: "Meaning-making act that connects evidence, context, language, and reader or viewer judgment.",
    definition_units: ["evidence", "context", "language", "judgment"],
    examples: ["text reading", "film reading", "art criticism"],
    non_examples: ["free association without support"],
    related_concepts: ["concept.reference", "theme.boundary"],
    common_misreadings: ["interpretation_equals_any_opinion"],
    negative_moves: ["do_not_invent_author_intent", "do_not_remove_evidence"],
    boundary_notes: ["Interpretation should preserve uncertainty when evidence is weak."],
    provenance: [P.sep("hermeneutics")],
    transfer_scope: ["literature", "film", "art", "philosophy"]
  }),
  conceptCard({
    id: "theme.language_parody",
    names: ["语言戏仿", "language parody"],
    domain: "literature.chinese_modern",
    factual_core: "Use of imitation, distortion, and register shift to expose a linguistic habit or authority.",
    definition_units: ["imitation", "distortion", "register_shift"],
    examples: ["bureaucratic tone mimicry", "classical-modern contrast"],
    non_examples: ["random joke", "mere sarcasm"],
    related_concepts: ["theme.naming", "concept.reference"],
    common_misreadings: ["parody_equals_mockery_only"],
    negative_moves: ["do_not_overread_every_style_shift_as_parody"],
    boundary_notes: ["Needs textual evidence; avoid claiming intent without support."],
    provenance: [P.official("Britannica:parody", "https://www.britannica.com/art/parody-literature")],
    transfer_scope: ["modern_literature", "film_dialogue", "public_language"]
  }),
  conceptCard({
    id: "theme.looking",
    names: ["观看", "looking", "viewing"],
    domain: "photography_history",
    factual_core: "Act of seeing shaped by angle, attention, medium, ethics, and social position.",
    definition_units: ["attention", "angle", "medium", "ethics"],
    examples: ["camera gaze", "viewer position"],
    non_examples: ["vision as biology only"],
    related_concepts: ["theme.framing", "concept.punctum"],
    common_misreadings: ["looking_equals_neutral_observation"],
    negative_moves: ["do_not_ignore_power_relation", "do_not_moralize_every_image"],
    boundary_notes: ["Use ethical caution for suffering images and private subjects."],
    provenance: [P.official("MoMA:photography", "https://www.moma.org/collection/terms/photography")],
    transfer_scope: ["photography", "film", "art", "media"]
  }),
  conceptCard({
    id: "theme.memory",
    names: ["记忆", "memory"],
    domain: "philosophy",
    factual_core: "Relation between past experience, selection, narration, object traces, and present meaning.",
    definition_units: ["past", "selection", "narration", "trace"],
    examples: ["childhood memory", "photographic memory trigger", "collective memory"],
    non_examples: ["archive fact only"],
    related_concepts: ["concept.narrative_memory", "theme.forgetting", "theme.youth_memory"],
    common_misreadings: ["memory_equals_fact_record"],
    negative_moves: ["do_not_treat_personal_memory_as_diagnosis"],
    boundary_notes: ["Personal disclosures need light uptake rather than clinical framing."],
    provenance: [P.sep("memory")],
    transfer_scope: ["literature", "music", "photography", "history"]
  }),
  conceptCard({
    id: "theme.modernization_loss",
    names: ["现代化失落", "modernization loss"],
    domain: "literature.chinese_modern",
    factual_core: "Perceived loss, displacement, or ambivalence produced by modernization and urban change.",
    definition_units: ["displacement", "ambivalence", "urban_change"],
    examples: ["town-city contrast", "vanishing local life"],
    non_examples: ["anti-modern claim by default"],
    related_concepts: ["theme.memory", "concept.city_street"],
    common_misreadings: ["modernization_equals_decline_only"],
    negative_moves: ["do_not_romanticize_poverty", "do_not_flatten_history"],
    boundary_notes: ["Keep historical specificity; avoid nostalgia as sole explanation."],
    provenance: [P.official("Britannica:modernization", "https://www.britannica.com/topic/modernization")],
    transfer_scope: ["music", "literature", "film", "city"]
  }),
  conceptCard({
    id: "theme.naming",
    names: ["命名", "naming"],
    domain: "philosophy",
    factual_core: "Act of assigning or using a name in relation to reference, identity, and social recognition.",
    definition_units: ["name", "reference", "identity", "recognition"],
    examples: ["person name", "work title", "category label"],
    non_examples: ["meaning in general"],
    related_concepts: ["concept.reference", "theme.language_parody"],
    common_misreadings: ["naming_equals_definition"],
    negative_moves: ["do_not_confuse_label_with_thing", "do_not_claim_names_settle_identity"],
    boundary_notes: ["Use for referent clarification and category distinction."],
    provenance: [P.sep("reference")],
    transfer_scope: ["philosophy", "literature", "identity_boundary", "translation"]
  }),
  conceptCard({
    id: "theme.refusal",
    names: ["拒绝", "refusal"],
    domain: "philosophy",
    factual_core: "A bounded no that may mark ethics, taste, safety, politics, or form.",
    definition_units: ["negative_choice", "limit", "stance"],
    examples: ["aesthetic refusal", "ethical refusal", "safety refusal"],
    non_examples: ["evasion", "silence by default"],
    related_concepts: ["theme.boundary", "theme.freedom_responsibility"],
    common_misreadings: ["refusal_equals_hostility"],
    negative_moves: ["do_not_refuse_when_answer_is_safe", "do_not_replace_dialogue_with_policy"],
    boundary_notes: ["Explain only as much as needed; preserve the original user need."],
    provenance: [P.sep("ethics-deontological")],
    transfer_scope: ["safety_boundary", "art", "political_language"]
  }),
  conceptCard({
    id: "theme.self_deception",
    names: ["自欺", "self-deception"],
    domain: "philosophy",
    factual_core: "Tension between what a subject knows, avoids, believes, or performs.",
    definition_units: ["avoidance", "belief", "performance", "self_relation"],
    examples: ["fictional narrator", "ethical evasiveness"],
    non_examples: ["simple mistake"],
    related_concepts: ["theme.freedom_responsibility", "concept.authenticity"],
    common_misreadings: ["self_deception_equals_lying"],
    negative_moves: ["do_not_accuse_user", "do_not_psychologize_without_request"],
    boundary_notes: ["Use primarily for texts and arguments, not user diagnosis."],
    provenance: [P.sep("self-deception")],
    transfer_scope: ["philosophy", "literature", "film"]
  }),
  conceptCard({
    id: "theme.youth_memory",
    names: ["青春记忆", "youthful memory"],
    domain: "music.mandopop",
    factual_core: "Cultural memory frame linking youth, school time, early feeling, and later retrospection.",
    definition_units: ["youth", "retrospection", "shared_memory"],
    examples: ["school-time song memory", "first-love retrospection"],
    non_examples: ["biographical childhood fact only"],
    related_concepts: ["theme.memory", "theme.modernization_loss", "concept.mono_no_aware"],
    common_misreadings: ["youth_memory_equals_literal_childhood"],
    negative_moves: ["do_not_reduce_song_to_autobiography", "do_not_force_nostalgia"],
    boundary_notes: ["For songs and literature, keep literal childhood separate from retrospective structure."],
    provenance: [P.official("Britannica:popular music", "https://www.britannica.com/art/popular-music")],
    transfer_scope: ["music", "literature", "film"]
  })
];

const stage1Concepts = [
  conceptCard({
    id: "concept.reference",
    names: ["指称", "reference"],
    domain: "philosophy",
    factual_core: "Relation between expression and what it picks out in context.",
    definition_units: ["expression", "referent", "context"],
    examples: ["pronoun referent", "proper name", "work title"],
    non_examples: ["all meaning", "speaker emotion"],
    related_concepts: ["theme.naming"],
    common_misreadings: ["reference_equals_theme"],
    negative_moves: ["do_not_change_referent_during_followup"],
    boundary_notes: ["Supports same-thing-or-not and pronoun questions."],
    provenance: [P.sep("reference")],
    transfer_scope: ["dialogue_binding", "literature", "philosophy"]
  }),
  conceptCard({
    id: "concept.translation",
    names: ["翻译", "translation"],
    domain: "language",
    factual_core: "Cross-language rendering shaped by meaning, form, context, and loss.",
    definition_units: ["meaning", "form", "context", "loss"],
    examples: ["title translation", "poetry translation"],
    non_examples: ["word substitution only"],
    related_concepts: ["concept.reference", "theme.interpretation"],
    common_misreadings: ["translation_equals_dictionary"],
    negative_moves: ["do_not_claim_one_perfect_equivalent"],
    boundary_notes: ["Mark when terms carry cultural context."],
    provenance: [P.official("Britannica:translation", "https://www.britannica.com/art/translation")],
    transfer_scope: ["literature", "film_titles", "philosophy_terms"]
  }),
  conceptCard({
    id: "concept.narrator_point_of_view",
    names: ["叙述者视角", "narrator point of view"],
    domain: "literature",
    factual_core: "Narrative relation among teller, viewpoint, distance, and knowledge.",
    definition_units: ["narrator", "viewpoint", "distance", "knowledge"],
    examples: ["first-person narrator", "limited viewpoint"],
    non_examples: ["author biography"],
    related_concepts: ["theme.framing", "theme.interpretation"],
    common_misreadings: ["narrator_equals_author"],
    negative_moves: ["do_not_infer_author_intent_from_narrator"],
    boundary_notes: ["Useful for fiction, film narration, and perspective claims."],
    provenance: [P.official("Britannica:narrative", "https://www.britannica.com/art/narrative")],
    transfer_scope: ["literature", "film", "photography"]
  }),
  conceptCard({
    id: "concept.form_material_institution",
    names: ["形式材料制度", "form material institution"],
    domain: "art_history",
    factual_core: "Triad for reading art and design through shape, medium, and recognition system.",
    definition_units: ["form", "material", "institution"],
    examples: ["readymade", "conceptual art", "design object"],
    non_examples: ["visual style only"],
    related_concepts: ["theme.institution", "concept.readymade"],
    common_misreadings: ["material_equals_meaning_alone"],
    negative_moves: ["do_not_ignore_institutional_frame"],
    boundary_notes: ["Do not use the triad as a universal answer for all art questions."],
    provenance: [P.moma("collection/terms/conceptual-art")],
    transfer_scope: ["art", "design", "photography"]
  }),
  conceptCard({
    id: "concept.negative_space",
    names: ["留白", "negative space"],
    domain: "art_history",
    factual_core: "Unused or unfilled area that shapes attention, rhythm, and implication.",
    definition_units: ["unfilled_area", "attention", "implication"],
    examples: ["visual blank area", "quiet pause", "cinematic offscreen space"],
    non_examples: ["empty content", "lack of craft"],
    related_concepts: ["theme.framing", "concept.restraint"],
    common_misreadings: ["negative_space_equals_nothing"],
    negative_moves: ["do_not_overapply_to_any_silence"],
    boundary_notes: ["Keep medium specificity: visual, cinematic, textual, musical."],
    provenance: [P.moma("learn/moma_learning/themes/what-is-modern-art/")],
    transfer_scope: ["design", "film", "literature", "music"]
  }),
  conceptCard({
    id: "concept.cold_affect",
    names: ["冷感", "cold affect"],
    domain: "literature.chinese_modern",
    factual_core: "A restrained emotional temperature produced by distance, irony, or precise detail.",
    definition_units: ["distance", "restraint", "irony", "detail"],
    examples: ["cool narrative tone", "dry urban observation"],
    non_examples: ["no emotion", "simple cruelty"],
    related_concepts: ["concept.restraint", "concept.bleakness"],
    common_misreadings: ["cold_affect_equals_indifference"],
    negative_moves: ["do_not_turn_every_restraint_into_coldness"],
    boundary_notes: ["Use as style axis, not as personality claim."],
    provenance: [P.brit("biography/Eileen-Chang")],
    transfer_scope: ["literature", "film", "music"]
  }),
  conceptCard({
    id: "concept.bleakness",
    names: ["苍凉", "bleakness"],
    domain: "literature.chinese_modern",
    factual_core: "Tone of cooled sorrow, historical pressure, and diminished expectation.",
    definition_units: ["sorrow", "historical_pressure", "low_expectation"],
    examples: ["war-era urban relation", "failed intimacy"],
    non_examples: ["romantic sadness only"],
    related_concepts: ["concept.cold_affect", "theme.memory"],
    common_misreadings: ["bleakness_equals_unique_to_one_author"],
    negative_moves: ["do_not_claim_exclusive_ownership"],
    boundary_notes: ["Mention parallels and differences when comparing authors or media."],
    provenance: [P.brit("biography/Eileen-Chang")],
    transfer_scope: ["literature", "film", "music"]
  }),
  conceptCard({
    id: "concept.city_street",
    names: ["城市街道", "city street"],
    domain: "urban",
    factual_core: "Urban public space where movement, encounter, commerce, memory, and visibility meet.",
    definition_units: ["movement", "encounter", "public_space", "visibility"],
    examples: ["sidewalk", "neighborhood street"],
    non_examples: ["traffic channel only"],
    related_concepts: ["concept.public_space", "concept.diversity_city"],
    common_misreadings: ["street_equals_road_engineering_only"],
    negative_moves: ["do_not_reduce_city_to_map"],
    boundary_notes: ["Urban claims need local specificity and avoid universal prescriptions."],
    provenance: [P.brit("biography/Jane-Jacobs")],
    transfer_scope: ["city", "film", "literature", "design"]
  }),
  conceptCard({
    id: "concept.heat_control",
    names: ["火候", "heat control"],
    domain: "food",
    factual_core: "Cooking judgment about timing, heat intensity, texture, and readiness.",
    definition_units: ["timing", "heat", "texture", "readiness"],
    examples: ["simmering", "searing", "resting"],
    non_examples: ["recipe step only", "food safety advice"],
    related_concepts: ["theme.interpretation"],
    common_misreadings: ["heat_control_equals_hotter"],
    negative_moves: ["do_not_give_food_safety_medical_advice"],
    boundary_notes: ["Use as process concept or analogy; avoid safety claims without source."],
    provenance: [P.official("Britannica:cooking", "https://www.britannica.com/topic/cooking")],
    transfer_scope: ["food", "craft", "music_timing", "film_pacing"]
  }),
  conceptCard({
    id: "concept.seasonality",
    names: ["季节感", "seasonality"],
    domain: "literature.japanese",
    factual_core: "Aesthetic structuring of time, feeling, scene, and cultural rhythm through seasonal signs.",
    definition_units: ["time_structure", "seasonal_sign", "feeling", "scene"],
    examples: ["kigo in haiku", "seasonal image", "ritual calendar"],
    non_examples: ["weather report", "temperature only"],
    related_concepts: ["concept.kigo_seasonality", "concept.mono_no_aware"],
    common_misreadings: ["seasonality_equals_weather"],
    negative_moves: ["do_not_route_to_history_only", "do_not_flatten_into_sadness"],
    boundary_notes: ["Use literary/aesthetic context when the concept was introduced there."],
    provenance: [P.official("Britannica:haiku", "https://www.britannica.com/art/haiku")],
    transfer_scope: ["Japanese_literature", "poetry", "film", "visual_culture"]
  }),
  conceptCard({
    id: "concept.rule_application_precedent",
    names: ["规则适用判例", "rule application precedent"],
    domain: "law_boundary",
    factual_core: "Legal reasoning scaffold for rules, application, precedent, and jurisdictional limits.",
    definition_units: ["rule", "application", "precedent", "jurisdiction"],
    examples: ["case distinction", "precedent constraint"],
    non_examples: ["personal legal advice", "single universal answer"],
    related_concepts: ["theme.boundary", "theme.institution"],
    common_misreadings: ["precedent_equals_current_outcome"],
    negative_moves: ["do_not_give_jurisdiction_specific_advice", "do_not_predict_case_result"],
    boundary_notes: ["Use for general legal reasoning only; preserve date and jurisdiction caveats."],
    provenance: [P.official("Oyez:about", "https://www.oyez.org/about")],
    transfer_scope: ["law_boundary", "argument_structure", "institutional_reasoning"]
  }),
  conceptCard({
    id: "concept.testimony",
    names: ["证言", "testimony"],
    domain: "film",
    factual_core: "A claim-bearing account whose reliability may depend on viewpoint, memory, motive, and context.",
    definition_units: ["account", "reliability", "viewpoint", "memory"],
    examples: ["court statement", "conflicting film account"],
    non_examples: ["objective camera truth"],
    related_concepts: ["concept.truth_claim", "concept.narrator_point_of_view"],
    common_misreadings: ["testimony_equals_truth"],
    negative_moves: ["do_not_treat_all_versions_as_equally_proven"],
    boundary_notes: ["Use for narrative reliability, not evidence advice."],
    provenance: [P.criterion("films/307-rashomon")],
    transfer_scope: ["film", "literature", "law_boundary"]
  }),
  conceptCard({
    id: "concept.truth_claim",
    names: ["真相主张", "truth claim"],
    domain: "philosophy",
    factual_core: "Assertion about what is true, requiring evidence, scope, and uncertainty control.",
    definition_units: ["claim", "evidence", "scope", "uncertainty"],
    examples: ["conflicting narratives", "historical claim"],
    non_examples: ["mood statement"],
    related_concepts: ["concept.testimony", "theme.interpretation"],
    common_misreadings: ["truth_claim_equals_final_truth"],
    negative_moves: ["do_not_overstate_support"],
    boundary_notes: ["Mark whether the answer is fact, interpretation, or analogy."],
    provenance: [P.sep("truth")],
    transfer_scope: ["film", "history", "law_boundary", "science"]
  }),
  conceptCard({
    id: "concept.restraint",
    names: ["克制", "restraint"],
    domain: "film",
    factual_core: "Form choice that withholds excess speech, action, or explanation to intensify attention.",
    definition_units: ["withholding", "attention", "tempo"],
    examples: ["held shot", "quiet dialogue", "minimal gesture"],
    non_examples: ["lack of content"],
    related_concepts: ["concept.negative_space", "concept.cold_affect"],
    common_misreadings: ["restraint_equals_emptiness"],
    negative_moves: ["do_not_praise_slowness_by_default"],
    boundary_notes: ["Tie restraint to a concrete medium feature."],
    provenance: [P.bfi("features")],
    transfer_scope: ["film", "literature", "music", "design"]
  }),
  conceptCard({
    id: "concept.longing",
    names: ["渴望", "longing"],
    domain: "film",
    factual_core: "Sustained desire shaped by absence, distance, time, or restraint.",
    definition_units: ["desire", "absence", "distance", "time"],
    examples: ["unresolved relation", "delayed encounter"],
    non_examples: ["instant preference"],
    related_concepts: ["concept.restraint", "theme.memory"],
    common_misreadings: ["longing_equals_romance_only"],
    negative_moves: ["do_not_make_private_claim_about_creator"],
    boundary_notes: ["Use as work-level affect, not as biography."],
    provenance: [P.criterion("films/198-in-the-mood-for-love")],
    transfer_scope: ["film", "music", "literature"]
  }),
  conceptCard({
    id: "concept.time_memory",
    names: ["时间记忆", "time and memory"],
    domain: "film",
    factual_core: "Relation of duration, recurrence, recollection, and historical or personal trace.",
    definition_units: ["duration", "recurrence", "recollection", "trace"],
    examples: ["elliptical film time", "remembered city"],
    non_examples: ["chronology only"],
    related_concepts: ["theme.memory", "concept.longing"],
    common_misreadings: ["time_equals_plot_order_only"],
    negative_moves: ["do_not_replace_context_with_mood"],
    boundary_notes: ["Separate historical time, plot time, and felt time."],
    provenance: [P.criterion("films/198-in-the-mood-for-love")],
    transfer_scope: ["film", "literature", "music"]
  }),
  conceptCard({
    id: "concept.punctum",
    names: ["刺点", "punctum"],
    domain: "photography_history",
    factual_core: "Photography concept for a detail that pierces or personally arrests the viewer.",
    definition_units: ["detail", "viewer_affect", "photographic_attention"],
    examples: ["minor detail with strong pull"],
    non_examples: ["general theme", "technical sharpness only"],
    related_concepts: ["theme.looking", "theme.memory"],
    common_misreadings: ["punctum_equals_every_detail"],
    negative_moves: ["do_not_claim_universal_punctum"],
    boundary_notes: ["Viewer-specific response should not become objective fact."],
    provenance: [P.official("Britannica:Roland Barthes", "https://www.britannica.com/biography/Roland-Gerard-Barthes")],
    transfer_scope: ["photography", "film_still", "memory"]
  }),
  conceptCard({
    id: "concept.readymade",
    names: ["现成品", "readymade"],
    domain: "art_history",
    factual_core: "Art strategy using selected manufactured objects to question authorship and institution.",
    definition_units: ["selection", "manufactured_object", "authorship", "institution"],
    examples: ["Fountain"],
    non_examples: ["handmade sculpture only"],
    related_concepts: ["concept.authorship", "theme.institution"],
    common_misreadings: ["readymade_equals_random_object"],
    negative_moves: ["do_not_ignore_context_of_selection"],
    boundary_notes: ["Use art-historical context; avoid saying any object is art by default."],
    provenance: [P.moma("collection/terms/readymade")],
    transfer_scope: ["art_history", "design", "institutional_theory"]
  }),
  conceptCard({
    id: "concept.authorship",
    names: ["作者性", "authorship"],
    domain: "art_history",
    factual_core: "Attribution and responsibility relation among maker, selection, institution, and audience.",
    definition_units: ["maker", "selection", "attribution", "responsibility"],
    examples: ["readymade authorship", "literary narrator distinction"],
    non_examples: ["private intention only"],
    related_concepts: ["concept.readymade", "theme.naming"],
    common_misreadings: ["authorship_equals_biography"],
    negative_moves: ["do_not_reduce_work_to_personality"],
    boundary_notes: ["Separate creator metadata from inferred private intent."],
    provenance: [P.moma("collection/terms/conceptual-art")],
    transfer_scope: ["art", "literature", "film"]
  }),
  conceptCard({
    id: "concept.object_image_language",
    names: ["物图像语言", "object image language"],
    domain: "art_history",
    factual_core: "Conceptual-art relation among physical thing, visual representation, and linguistic sign.",
    definition_units: ["object", "image", "language", "sign"],
    examples: ["One and Three Chairs"],
    non_examples: ["three copies of one object"],
    related_concepts: ["concept.reference", "concept.form_material_institution"],
    common_misreadings: ["object_image_language_equals_synonym"],
    negative_moves: ["do_not_collapse_sign_and_object"],
    boundary_notes: ["Use for representation questions; avoid opaque jargon."],
    provenance: [P.moma("collection/works/81435")],
    transfer_scope: ["conceptual_art", "language", "design"]
  }),
  conceptCard({
    id: "concept.public_space",
    names: ["公共空间", "public space"],
    domain: "urban",
    factual_core: "Shared urban space shaped by access, visibility, use, encounter, and conflict.",
    definition_units: ["access", "visibility", "use", "encounter"],
    examples: ["street", "sidewalk", "park"],
    non_examples: ["private interior only"],
    related_concepts: ["concept.city_street", "concept.diversity_city"],
    common_misreadings: ["public_space_equals_empty_space"],
    negative_moves: ["do_not_ignore_exclusion_or_access"],
    boundary_notes: ["Urban claims should mark local and historical context."],
    provenance: [P.brit("biography/Jane-Jacobs")],
    transfer_scope: ["urban", "film", "literature"]
  }),
  conceptCard({
    id: "concept.diversity_city",
    names: ["城市多样性", "urban diversity"],
    domain: "urban",
    factual_core: "Mixture of uses, people, times, and scales that shapes city vitality and friction.",
    definition_units: ["mixed_use", "people", "time", "scale"],
    examples: ["mixed street life", "varied building age"],
    non_examples: ["branding variety only"],
    related_concepts: ["concept.city_street", "concept.public_space"],
    common_misreadings: ["diversity_equals_decoration"],
    negative_moves: ["do_not_romanticize_inequality"],
    boundary_notes: ["Keep policy claims bounded and locally specific."],
    provenance: [P.brit("biography/Jane-Jacobs")],
    transfer_scope: ["urban", "design", "film_location"]
  })
];

const persons = [
  personCard({
    id: "person.akira_kurosawa",
    names: ["黑泽明", "Akira Kurosawa"],
    domain: "film.japanese",
    roles: ["film director", "screenwriter"],
    period: "20th_century",
    regions_languages: ["Japan", "Japanese"],
    representative_works: ["work.rashomon_kurosawa", "work.seven_samurai"],
    themes: ["testimony", "ethics", "action_form"],
    style_axes: ["movement", "weather", "moral_conflict"],
    related_concepts: ["concept.testimony", "concept.truth_claim"],
    related_people: ["person.ozu_yasujiro"],
    negative_moves: ["do_not_make_all_Japanese_cinema_Kurosawa_like"],
    uncertainty_notes: ["Use work-level evidence for influence claims."],
    provenance: [P.criterion("films/307-rashomon")],
    transfer_scope: ["film_comparison", "perspective_questions", "representative_works"]
  }),
  personCard({
    id: "person.edward_yang",
    names: ["杨德昌", "Edward Yang"],
    domain: "film.taiwan",
    roles: ["film director"],
    period: "late_20th_century",
    regions_languages: ["Taiwan", "Mandarin"],
    representative_works: ["work.a_brighter_summer_day", "work.yi_yi"],
    themes: ["urban_modernity", "family", "history"],
    style_axes: ["ensemble_structure", "urban_space", "social_observation"],
    related_concepts: ["theme.modernization_loss", "concept.city_street"],
    related_people: ["person.hou_hsiao_hsien"],
    negative_moves: ["do_not_collapse_Taiwan_New_Cinema_into_one_style"],
    uncertainty_notes: ["Work availability and titles vary by market."],
    provenance: [P.criterion("films/28596-a-brighter-summer-day")],
    transfer_scope: ["film_comparison", "city_film", "topic_reentry"]
  }),
  personCard({
    id: "person.wong_kar_wai",
    names: ["王家卫", "Wong Kar-wai"],
    domain: "film.hongkong",
    roles: ["film director"],
    period: "late_20th_century",
    regions_languages: ["Hong Kong", "Cantonese", "Mandarin"],
    representative_works: ["work.in_the_mood_for_love"],
    themes: ["longing", "memory", "urban_time"],
    style_axes: ["restraint", "music", "elliptical_time"],
    related_concepts: ["concept.longing", "concept.time_memory"],
    related_people: ["person.hou_hsiao_hsien"],
    negative_moves: ["do_not_reduce_style_to_pretty_mood"],
    uncertainty_notes: ["Compare by film form, not only atmosphere."],
    provenance: [P.criterion("films/198-in-the-mood-for-love")],
    transfer_scope: ["film_music_bridge", "memory_discussion", "style_comparison"]
  }),
  personCard({
    id: "person.ann_hui",
    names: ["许鞍华", "Ann Hui"],
    domain: "film.hongkong",
    roles: ["film director"],
    period: "late_20th_century",
    regions_languages: ["Hong Kong", "Chinese"],
    representative_works: ["work.boat_people"],
    themes: ["history", "migration", "ordinary_life"],
    style_axes: ["social_observation", "historical_pressure"],
    related_concepts: ["theme.memory", "concept.public_space"],
    related_people: ["person.wong_kar_wai"],
    negative_moves: ["do_not_reduce_Hong_Kong_cinema_to_one_aesthetic"],
    uncertainty_notes: ["Historical context should stay bounded."],
    provenance: [P.bfi("interviews/ann-hui")],
    transfer_scope: ["film_history", "women_directors", "social_context"]
  }),
  personCard({
    id: "person.jia_zhangke",
    names: ["贾樟柯", "Jia Zhangke"],
    domain: "film.chinese",
    roles: ["film director"],
    period: "contemporary",
    regions_languages: ["China", "Mandarin"],
    representative_works: ["work.still_life_jia"],
    themes: ["modernization_loss", "migration", "place"],
    style_axes: ["long_take", "location", "social_change"],
    related_concepts: ["theme.modernization_loss", "concept.city_street"],
    related_people: ["person.hou_hsiao_hsien"],
    negative_moves: ["do_not_turn_social_change_into_single_mood"],
    uncertainty_notes: ["Keep political claims sourced and bounded."],
    provenance: [P.bfi("features/jia-zhangke")],
    transfer_scope: ["film_city", "modernization_discussion", "work_comparison"]
  }),
  personCard({
    id: "person.koreeda_hirokazu",
    names: ["是枝裕和", "Hirokazu Kore-eda"],
    domain: "film.japanese",
    roles: ["film director"],
    period: "contemporary",
    regions_languages: ["Japan", "Japanese"],
    representative_works: ["work.still_walking"],
    themes: ["family", "memory", "ordinary_life"],
    style_axes: ["quiet_observation", "domestic_time"],
    related_concepts: ["theme.memory", "concept.restraint"],
    related_people: ["person.ozu_yasujiro"],
    negative_moves: ["do_not_equate_quiet_family_film_with_Ozu"],
    uncertainty_notes: ["Comparisons to Ozu should be framed as affinity, not identity."],
    provenance: [P.criterion("films/27540-still-walking")],
    transfer_scope: ["family_film", "Japanese_film_comparison", "memory_questions"]
  }),
  personCard({
    id: "person.virginia_woolf",
    names: ["弗吉尼亚·伍尔夫", "Virginia Woolf"],
    domain: "literature.western_modern",
    roles: ["novelist", "essayist"],
    period: "modernism",
    regions_languages: ["Britain", "English"],
    representative_works: ["work.to_the_lighthouse", "work.mrs_dalloway"],
    themes: ["consciousness", "time", "gender"],
    style_axes: ["interior_time", "stream_of_consciousness"],
    related_concepts: ["concept.time_memory", "concept.narrator_point_of_view"],
    related_people: ["person.joyce"],
    negative_moves: ["do_not_reduce_modernism_to_difficulty"],
    uncertainty_notes: ["Use text-level claims, not biography as explanation."],
    provenance: [P.brit("biography/Virginia-Woolf")],
    transfer_scope: ["modernism", "narration", "time_memory"]
  }),
  personCard({
    id: "person.t_s_eliot",
    names: ["T. S. Eliot", "T.S. 艾略特"],
    domain: "literature.western_modern",
    roles: ["poet", "critic"],
    period: "modernism",
    regions_languages: ["United States", "Britain", "English"],
    representative_works: ["work.the_waste_land"],
    themes: ["fragmentation", "tradition", "modernity"],
    style_axes: ["allusion", "collage", "cultural_memory"],
    related_concepts: ["theme.memory", "theme.interpretation"],
    related_people: ["person.joyce"],
    negative_moves: ["do_not_quote_poems_at_length"],
    uncertainty_notes: ["Allusion claims need caution."],
    provenance: [P.brit("biography/T-S-Eliot")],
    transfer_scope: ["poetry", "modernism", "fragmentation"]
  }),
  personCard({
    id: "person.ferdinand_de_saussure",
    names: ["索绪尔", "Ferdinand de Saussure"],
    domain: "language",
    roles: ["linguist"],
    period: "early_20th_century",
    regions_languages: ["Switzerland", "French"],
    representative_works: ["work.course_in_general_linguistics"],
    themes: ["sign", "language_structure", "difference"],
    style_axes: ["signifier_signified", "structural_relation"],
    related_concepts: ["concept.reference", "theme.naming"],
    related_people: ["person.ludwig_wittgenstein"],
    negative_moves: ["do_not_treat_sign_as_simple_label"],
    uncertainty_notes: ["Keep linguistic and philosophical uses distinct."],
    provenance: [P.brit("biography/Ferdinand-de-Saussure")],
    transfer_scope: ["language", "reference_questions", "translation"]
  }),
  personCard({
    id: "person.ludwig_wittgenstein",
    names: ["维特根斯坦", "Ludwig Wittgenstein"],
    domain: "philosophy",
    roles: ["philosopher"],
    period: "20th_century",
    regions_languages: ["Austria", "Britain", "German", "English"],
    representative_works: ["work.philosophical_investigations"],
    themes: ["language_use", "meaning", "forms_of_life"],
    style_axes: ["ordinary_language", "example_based_reasoning"],
    related_concepts: ["concept.reference", "theme.naming"],
    related_people: ["person.ferdinand_de_saussure"],
    negative_moves: ["do_not_use_as_generic_language_authority"],
    uncertainty_notes: ["Separate early and later Wittgenstein when needed."],
    provenance: [P.sep("wittgenstein")],
    transfer_scope: ["language", "philosophy", "ordinary_meaning"]
  }),
  personCard({
    id: "person.jane_jacobs",
    names: ["简·雅各布斯", "Jane Jacobs"],
    domain: "urban",
    roles: ["urban writer", "activist"],
    period: "20th_century",
    regions_languages: ["United States", "Canada", "English"],
    representative_works: ["work.death_and_life_great_american_cities"],
    themes: ["street_life", "public_space", "urban_diversity"],
    style_axes: ["sidewalk_observation", "mixed_use"],
    related_concepts: ["concept.city_street", "concept.diversity_city"],
    related_people: [],
    negative_moves: ["do_not_turn_city_observation_into_universal_policy"],
    uncertainty_notes: ["Planning claims depend on city context."],
    provenance: [P.brit("biography/Jane-Jacobs")],
    transfer_scope: ["city", "film_space", "design"]
  }),
  personCard({
    id: "person.charles_eames",
    names: ["查尔斯·伊姆斯", "Charles Eames"],
    domain: "design_history",
    roles: ["designer", "architect"],
    period: "20th_century",
    regions_languages: ["United States", "English"],
    representative_works: ["work.eames_lounge_chair"],
    themes: ["industrial_design", "materials", "everyday_use"],
    style_axes: ["molded_material", "usefulness", "play"],
    related_concepts: ["concept.form_material_institution"],
    related_people: ["person.ray_eames"],
    negative_moves: ["do_not_separate_design_from_use"],
    uncertainty_notes: ["Credit collaborative practice with Ray Eames."],
    provenance: [P.official("Eames Office:Charles and Ray", "https://www.eamesoffice.com/charles-and-ray/")],
    transfer_scope: ["design", "material_culture", "modernism"]
  }),
  personCard({
    id: "person.ray_eames",
    names: ["雷·伊姆斯", "Ray Eames"],
    domain: "design_history",
    roles: ["designer", "artist"],
    period: "20th_century",
    regions_languages: ["United States", "English"],
    representative_works: ["work.eames_lounge_chair"],
    themes: ["industrial_design", "materials", "visual_culture"],
    style_axes: ["collaboration", "material_experiment"],
    related_concepts: ["concept.form_material_institution"],
    related_people: ["person.charles_eames"],
    negative_moves: ["do_not_erase_collaborative_authorship"],
    uncertainty_notes: ["Avoid attributing all Eames work to Charles alone."],
    provenance: [P.official("Eames Office:Charles and Ray", "https://www.eamesoffice.com/charles-and-ray/")],
    transfer_scope: ["design", "authorship", "collaboration"]
  }),
  personCard({
    id: "person.dieter_rams",
    names: ["迪特·拉姆斯", "Dieter Rams"],
    domain: "design_history",
    roles: ["industrial designer"],
    period: "20th_century",
    regions_languages: ["Germany", "German"],
    representative_works: ["work.braun_skj4"],
    themes: ["industrial_design", "restraint", "usability"],
    style_axes: ["clarity", "function", "material"],
    related_concepts: ["concept.form_material_institution", "concept.negative_space"],
    related_people: ["person.walter_gropius"],
    negative_moves: ["do_not_equate_restraint_with_empty_minimalism"],
    uncertainty_notes: ["Use stable design principles; avoid brand mythology."],
    provenance: [P.official("Vitsoe:Dieter Rams", "https://www.vitsoe.com/us/about/dieter-rams")],
    transfer_scope: ["design", "minimalism_contrast", "usability"]
  })
];

const works = [
  workCard({
    id: "work.diary_of_a_madman",
    names: ["狂人日记", "Diary of a Madman"],
    domain: "literature.chinese_modern",
    creator_ids: ["person.lu_xun"],
    work_type: "short_story",
    period: "may_fourth",
    factual_core: "Lu Xun story associated with vernacular modern fiction and social critique.",
    themes: ["vernacular", "critique", "modern_subject"],
    style_axes: ["diary_form", "irony", "social_allegory"],
    related_concepts: ["theme.language_parody", "theme.interpretation"],
    provenance: [P.brit("biography/Lu-Xun")],
    transfer_scope: ["representative_work", "modern_literature", "narrator_question"]
  }),
  workCard({
    id: "work.half_a_lifelong_romance",
    names: ["半生缘", "Half a Lifelong Romance"],
    domain: "literature.chinese_modern",
    creator_ids: ["person.eileen_chang"],
    work_type: "novel",
    period: "modern_chinese_literature",
    factual_core: "Eileen Chang novel linked to urban relation, time, and damaged intimacy.",
    themes: ["urban_relation", "time", "gender"],
    style_axes: ["cool_detail", "compressed_emotion"],
    related_concepts: ["concept.cold_affect", "concept.bleakness"],
    provenance: [P.brit("biography/Eileen-Chang")],
    transfer_scope: ["representative_work", "style_discussion", "modern_literature"]
  }),
  workCard({
    id: "work.moon_represents_my_heart",
    names: ["月亮代表我的心", "The Moon Represents My Heart"],
    domain: "music.taiwan",
    creator_ids: ["person.teresa_teng"],
    work_type: "song",
    period: "taiwan_pop_1970s",
    factual_core: "Teresa Teng-associated song anchor for Mandarin pop tenderness and cross-regional circulation.",
    themes: ["romance", "Mandarin_pop", "cross_regional_memory"],
    style_axes: ["melody", "vocal_intimacy"],
    related_concepts: ["theme.memory"],
    provenance: [P.official("Britannica:Teresa Teng", "https://www.britannica.com/biography/Teresa-Teng")],
    transfer_scope: ["representative_song", "music_memory", "Mandarin_pop"]
  }),
  workCard({
    id: "work.nothing_to_my_name",
    names: ["一无所有", "Nothing to My Name"],
    domain: "music.mainland_rock",
    creator_ids: ["person.cui_jian"],
    work_type: "song",
    period: "mainland_rock_1980s",
    factual_core: "Cui Jian-associated song anchor for Chinese rock and public generational feeling.",
    themes: ["rock", "youth", "public_voice"],
    style_axes: ["direct_voice", "rock_arrangement"],
    related_concepts: ["theme.youth_memory"],
    provenance: [P.official("Britannica:rock music", "https://www.britannica.com/art/rock-music")],
    transfer_scope: ["representative_song", "Chinese_rock", "generational_memory"]
  }),
  workCard({
    id: "work.album_jay",
    names: ["Jay", "《Jay》"],
    domain: "music.chinese_pop_general",
    creator_ids: ["person.jay_chou"],
    work_type: "album",
    period: "mandopop_2000s",
    factual_core: "Debut album associated with Jay Chou and early-2000s Mandopop style mixing.",
    themes: ["Mandopop", "R_and_B", "youth"],
    style_axes: ["melody", "rhythm", "arrangement"],
    related_concepts: ["concept.music_chinese_pop_general"],
    provenance: [P.official("Britannica:popular music", "https://www.britannica.com/art/popular-music")],
    transfer_scope: ["album_vs_single", "Mandopop", "representative_album"]
  }),
  workCard({
    id: "work.tale_of_genji",
    names: ["源氏物语", "The Tale of Genji"],
    domain: "literature.japanese",
    creator_ids: ["person.murasaki_shikibu"],
    work_type: "novel_classic",
    period: "heian_literature",
    factual_core: "Heian Japanese classic associated with court life, feeling, and narrative complexity.",
    themes: ["court_life", "mono_no_aware", "time"],
    style_axes: ["narrative_detail", "emotional_refinement"],
    related_concepts: ["concept.mono_no_aware", "concept.seasonality"],
    provenance: [P.brit("topic/The-Tale-of-Genji")],
    transfer_scope: ["Japanese_classic", "representative_work", "mono_no_aware"]
  }),
  workCard({
    id: "work.ulysses",
    names: ["尤利西斯", "Ulysses"],
    domain: "literature.western_modern",
    creator_ids: ["person.joyce"],
    work_type: "novel",
    period: "modernism",
    factual_core: "Modernist novel associated with one-day structure, language experiment, and consciousness.",
    themes: ["modernism", "consciousness", "language"],
    style_axes: ["stream_of_consciousness", "formal_experiment"],
    related_concepts: ["concept.narrator_point_of_view", "concept.time_memory"],
    provenance: [P.brit("topic/Ulysses-novel-by-Joyce")],
    transfer_scope: ["modernism", "narration", "language_form"]
  }),
  workCard({
    id: "work.the_waste_land",
    names: ["荒原", "The Waste Land"],
    domain: "literature.western_modern",
    creator_ids: ["person.t_s_eliot"],
    work_type: "poem",
    period: "modernism",
    factual_core: "Modernist poem associated with fragmentation, allusion, and postwar cultural dislocation.",
    themes: ["fragmentation", "allusion", "modernity"],
    style_axes: ["collage", "voice_shift"],
    related_concepts: ["theme.interpretation", "theme.memory"],
    provenance: [P.brit("topic/The-Waste-Land")],
    transfer_scope: ["modernism", "poetry", "fragmentation"]
  }),
  workCard({
    id: "work.rashomon_kurosawa",
    names: ["罗生门", "Rashomon"],
    domain: "film.japanese",
    creator_ids: ["person.akira_kurosawa"],
    work_type: "film",
    period: "postwar_japanese_cinema",
    factual_core: "Kurosawa film anchor for conflicting testimony, perspective, and truth claims.",
    themes: ["testimony", "perspective", "truth_claim"],
    style_axes: ["multiple_accounts", "forest_space"],
    related_concepts: ["concept.testimony", "concept.truth_claim"],
    provenance: [P.criterion("films/307-rashomon")],
    transfer_scope: ["film_perspective", "truth_claim", "work_comparison"]
  }),
  workCard({
    id: "work.seven_samurai",
    names: ["七武士", "Seven Samurai"],
    domain: "film.japanese",
    creator_ids: ["person.akira_kurosawa"],
    work_type: "film",
    period: "postwar_japanese_cinema",
    factual_core: "Kurosawa film anchor for group action, ethics, weather, and social order.",
    themes: ["group_action", "ethics", "class"],
    style_axes: ["movement", "editing", "rain"],
    related_concepts: ["theme.freedom_responsibility"],
    provenance: [P.criterion("films/165-seven-samurai")],
    transfer_scope: ["film_action", "ethics", "representative_work"]
  }),
  workCard({
    id: "work.a_brighter_summer_day",
    names: ["牯岭街少年杀人事件", "A Brighter Summer Day"],
    domain: "film.taiwan",
    creator_ids: ["person.edward_yang"],
    work_type: "film",
    period: "Taiwan_New_Cinema",
    factual_core: "Edward Yang film anchor for youth, family, history, and urban social pressure.",
    themes: ["youth", "history", "urban_pressure"],
    style_axes: ["ensemble", "duration", "social_space"],
    related_concepts: ["theme.youth_memory", "theme.modernization_loss"],
    provenance: [P.criterion("films/28596-a-brighter-summer-day")],
    transfer_scope: ["Taiwan_cinema", "youth_memory", "film_history"]
  }),
  workCard({
    id: "work.in_the_mood_for_love",
    names: ["花样年华", "In the Mood for Love"],
    domain: "film.hongkong",
    creator_ids: ["person.wong_kar_wai"],
    work_type: "film",
    period: "Hong_Kong_cinema_2000s",
    factual_core: "Wong Kar-wai film anchor for restraint, longing, repetition, and time.",
    themes: ["longing", "restraint", "time"],
    style_axes: ["music", "costume", "elliptical_time"],
    related_concepts: ["concept.longing", "concept.restraint", "concept.time_memory"],
    provenance: [P.criterion("films/198-in-the-mood-for-love")],
    transfer_scope: ["film_music_bridge", "style_discussion", "memory"]
  }),
  workCard({
    id: "work.boat_people",
    names: ["投奔怒海", "Boat People"],
    domain: "film.hongkong",
    creator_ids: ["person.ann_hui"],
    work_type: "film",
    period: "Hong_Kong_New_Wave",
    factual_core: "Ann Hui film anchor for history, migration, observation, and political context.",
    themes: ["history", "migration", "social_context"],
    style_axes: ["observational_pressure", "political_context"],
    related_concepts: ["theme.memory", "theme.boundary"],
    provenance: [P.bfi("interviews/ann-hui")],
    transfer_scope: ["Hong_Kong_cinema", "history_boundary", "film_context"]
  }),
  workCard({
    id: "work.still_life_jia",
    names: ["三峡好人", "Still Life"],
    domain: "film.chinese",
    creator_ids: ["person.jia_zhangke"],
    work_type: "film",
    period: "contemporary_chinese_cinema",
    factual_core: "Jia Zhangke film anchor for displacement, place, and modernization change.",
    themes: ["displacement", "place", "modernization_loss"],
    style_axes: ["location", "long_take", "social_change"],
    related_concepts: ["theme.modernization_loss", "concept.city_street"],
    provenance: [P.bfi("features/jia-zhangke")],
    transfer_scope: ["modernization", "film_city", "work_comparison"]
  }),
  workCard({
    id: "work.still_walking",
    names: ["步履不停", "Still Walking"],
    domain: "film.japanese",
    creator_ids: ["person.koreeda_hirokazu"],
    work_type: "film",
    period: "contemporary_Japanese_cinema",
    factual_core: "Kore-eda film anchor for family time, memory, ordinary detail, and restraint.",
    themes: ["family", "memory", "ordinary_detail"],
    style_axes: ["domestic_time", "quiet_observation"],
    related_concepts: ["theme.memory", "concept.restraint"],
    provenance: [P.criterion("films/27540-still-walking")],
    transfer_scope: ["family_film", "memory", "Japanese_cinema"]
  }),
  workCard({
    id: "work.one_and_three_chairs",
    names: ["One and Three Chairs", "一把和三把椅子"],
    domain: "art_history",
    creator_ids: ["person.joseph_kosuth"],
    work_type: "artwork",
    period: "conceptual_art",
    factual_core: "Conceptual artwork anchor for object, image, language, and reference.",
    themes: ["conceptual_art", "reference", "language"],
    style_axes: ["object_image_language", "institution"],
    related_concepts: ["concept.object_image_language", "concept.reference"],
    provenance: [P.moma("collection/works/81435")],
    transfer_scope: ["conceptual_art", "language", "reference"]
  }),
  workCard({
    id: "work.bauhaus_building",
    names: ["包豪斯校舍", "Bauhaus Building"],
    domain: "design_history",
    creator_ids: ["person.walter_gropius"],
    work_type: "building",
    period: "Bauhaus",
    factual_core: "Dessau Bauhaus building anchor for modern design, school, workshop, and institution.",
    themes: ["Bauhaus", "modern_design", "institution"],
    style_axes: ["form", "function", "material"],
    related_concepts: ["theme.institution", "concept.form_material_institution"],
    provenance: [P.official("Bauhaus Dessau:building", "https://www.bauhaus-dessau.de/en/architecture/bauhaus-building.html")],
    transfer_scope: ["design_history", "architecture", "institution"]
  }),
  workCard({
    id: "work.death_and_life_great_american_cities",
    names: ["The Death and Life of Great American Cities", "美国大城市的死与生"],
    domain: "urban",
    creator_ids: ["person.jane_jacobs"],
    work_type: "book",
    period: "20th_century_urbanism",
    factual_core: "Jane Jacobs book anchor for street life, mixed use, public space, and urban observation.",
    themes: ["street_life", "public_space", "diversity"],
    style_axes: ["sidewalk_observation", "mixed_use"],
    related_concepts: ["concept.city_street", "concept.public_space", "concept.diversity_city"],
    provenance: [P.brit("biography/Jane-Jacobs")],
    transfer_scope: ["urbanism", "city_film_bridge", "public_space"]
  }),
  workCard({
    id: "work.the_golden_cangue",
    names: ["金锁记", "The Golden Cangue"],
    domain: "literature.chinese_modern",
    creator_ids: ["person.eileen_chang"],
    work_type: "novella",
    period: "modern_chinese_literature",
    factual_core: "Eileen Chang work anchor for family pressure, money, gender, and bleak restraint.",
    themes: ["family", "gender", "bleakness"],
    style_axes: ["cold_affect", "compressed_detail"],
    related_concepts: ["concept.cold_affect", "concept.bleakness"],
    provenance: [P.brit("biography/Eileen-Chang")],
    transfer_scope: ["representative_work", "style_discussion", "modern_literature"]
  }),
  workCard({
    id: "work.red_rose_white_rose",
    names: ["红玫瑰与白玫瑰", "Red Rose, White Rose"],
    domain: "literature.chinese_modern",
    creator_ids: ["person.eileen_chang"],
    work_type: "story",
    period: "modern_chinese_literature",
    factual_core: "Eileen Chang work anchor for gendered desire, social role, and ironic contrast.",
    themes: ["gender", "desire", "social_role"],
    style_axes: ["irony", "contrast", "cool_detail"],
    related_concepts: ["concept.cold_affect", "theme.interpretation"],
    provenance: [P.brit("biography/Eileen-Chang")],
    transfer_scope: ["representative_work", "gender_relation", "modern_literature"]
  }),
  workCard({
    id: "work.lust_caution",
    names: ["色，戒", "Lust, Caution"],
    domain: "literature.chinese_modern",
    creator_ids: ["person.eileen_chang"],
    work_type: "story",
    period: "modern_chinese_literature",
    factual_core: "Eileen Chang story anchor for wartime relation, performance, danger, and ambiguity.",
    themes: ["war", "performance", "ambiguity"],
    style_axes: ["restraint", "danger", "irony"],
    related_concepts: ["concept.cold_affect", "theme.boundary"],
    provenance: [P.brit("biography/Eileen-Chang")],
    transfer_scope: ["representative_work", "war_context", "adaptation_discussion"]
  })
];

const closureConcepts = [
  conceptCard({
    id: "concept.mono_no_aware",
    names: ["物哀", "mono no aware"],
    domain: "literature.japanese",
    factual_core: "Japanese aesthetic concept for sensitivity to transience and the pathos of things.",
    definition_units: ["transience", "sensitivity", "pathos", "recognition"],
    examples: ["seasonal passing", "parting scene", "Heian court feeling"],
    non_examples: ["sadness in general", "personal depression"],
    related_concepts: ["concept.mujo_impermanence", "concept.seasonality", "concept.wabi_sabi"],
    common_misreadings: ["mono_no_aware_equals_sadness"],
    negative_moves: ["do_not_flatten_into_sadness", "do_not_treat_as_identical_to_wabi_sabi"],
    boundary_notes: ["Use as aesthetic structure; do not claim all Japanese literature has one mood."],
    provenance: [P.official("Britannica:Tale of Genji", "https://www.britannica.com/topic/The-Tale-of-Genji")],
    transfer_scope: ["Japanese_literature", "film_mood", "music_memory"]
  }),
  conceptCard({
    id: "concept.mujo_impermanence",
    names: ["无常", "mujō", "impermanence"],
    domain: "literature.japanese",
    factual_core: "Buddhist and aesthetic term for change, perishability, and non-permanence.",
    definition_units: ["change", "perishability", "non_permanence"],
    examples: ["passing seasons", "vanishing relation", "historical decline"],
    non_examples: ["fatalism", "sadness only"],
    related_concepts: ["concept.mono_no_aware", "concept.wabi_sabi", "concept.seasonality"],
    common_misreadings: ["impermanence_equals_fatalism"],
    negative_moves: ["do_not_make_change_sound_like_destiny", "do_not_merge_with_mono_no_aware"],
    boundary_notes: ["Separate ontology of change from emotional response to change."],
    provenance: [P.official("Britannica:Buddhism", "https://www.britannica.com/topic/Buddhism")],
    transfer_scope: ["Japanese_literature", "philosophy", "film"]
  }),
  conceptCard({
    id: "concept.kigo_seasonality",
    names: ["季语", "kigo"],
    domain: "literature.japanese",
    factual_core: "Haiku-related seasonal word or sign that locates feeling, time, and scene.",
    definition_units: ["seasonal_word", "time", "scene", "feeling"],
    examples: ["spring image", "autumn image", "seasonal plant"],
    non_examples: ["weather report", "calendar date only"],
    related_concepts: ["concept.seasonality", "concept.mono_no_aware"],
    common_misreadings: ["kigo_equals_weather"],
    negative_moves: ["do_not_reduce_to_temperature", "do_not_force_kigo_into_all_poems"],
    boundary_notes: ["Use specifically for poetry/haiku contexts unless an analogy is explicit."],
    provenance: [P.official("Britannica:haiku", "https://www.britannica.com/art/haiku")],
    transfer_scope: ["haiku", "poetry", "visual_culture"]
  }),
  conceptCard({
    id: "movement.taiwan_new_cinema",
    entity_type: "movement",
    names: ["台湾新电影", "Taiwan New Cinema"],
    domain: "film.taiwan",
    factual_core: "Taiwan film movement associated with historical memory, everyday life, and new narrative forms.",
    definition_units: ["Taiwan_film", "history", "everyday_life", "new_form"],
    examples: ["Hou Hsiao-hsien", "Edward Yang"],
    non_examples: ["all Taiwan film", "single director style"],
    related_concepts: ["theme.memory", "theme.modernization_loss"],
    related_people: ["person.hou_hsiao_hsien", "person.edward_yang"],
    common_misreadings: ["movement_equals_one_visual_style"],
    negative_moves: ["do_not_collapse_directors_together"],
    boundary_notes: ["Use movement context, then return to concrete works when asked."],
    provenance: [P.criterion("films/28596-a-brighter-summer-day")],
    transfer_scope: ["film_history", "director_comparison", "Taiwan_culture"]
  })
];

const closurePersons = [
  personCard({
    id: "person.ozu_yasujiro",
    names: ["小津安二郎", "Yasujirō Ozu", "Ozu Yasujiro"],
    domain: "film.japanese",
    roles: ["film director", "screenwriter"],
    period: "20th_century",
    regions_languages: ["Japan", "Japanese"],
    representative_works: ["work.tokyo_story", "work.late_spring"],
    themes: ["family", "time", "ordinary_life"],
    style_axes: ["low_camera", "restraint", "domestic_space"],
    related_concepts: ["concept.restraint", "theme.memory"],
    related_people: ["person.akira_kurosawa", "person.koreeda_hirokazu"],
    negative_moves: ["do_not_reduce_Ozu_to_slowness"],
    uncertainty_notes: ["Use film-specific evidence for style claims."],
    provenance: [P.criterion("films/284-tokyo-story")],
    transfer_scope: ["film_comparison", "slowness_questions", "family_memory"]
  }),
  personCard({
    id: "person.hou_hsiao_hsien",
    names: ["侯孝贤", "Hou Hsiao-hsien"],
    domain: "film.taiwan",
    roles: ["film director"],
    period: "late_20th_century",
    regions_languages: ["Taiwan", "Mandarin", "Hokkien"],
    representative_works: ["work.a_city_of_sadness"],
    themes: ["history", "memory", "everyday_life"],
    style_axes: ["long_take", "distance", "historical_space"],
    related_concepts: ["theme.memory", "movement.taiwan_new_cinema"],
    related_people: ["person.edward_yang", "person.wong_kar_wai"],
    negative_moves: ["do_not_make_slowness_the_only_point"],
    uncertainty_notes: ["Historical interpretation should stay bounded."],
    provenance: [P.official("Britannica:Hou Hsiao-hsien", "https://www.britannica.com/biography/Hou-Hsiao-hsien")],
    transfer_scope: ["Taiwan_cinema", "history_film", "slowness_comparison"]
  }),
  personCard({
    id: "person.joseph_kosuth",
    names: ["约瑟夫·科苏斯", "Joseph Kosuth"],
    domain: "art_history",
    roles: ["conceptual artist"],
    period: "conceptual_art",
    regions_languages: ["United States", "English"],
    representative_works: ["work.one_and_three_chairs"],
    themes: ["conceptual_art", "language", "reference"],
    style_axes: ["object_image_language", "institution"],
    related_concepts: ["concept.object_image_language", "concept.reference"],
    related_people: ["person.duchamp"],
    negative_moves: ["do_not_treat_conceptual_art_as_word_puzzle_only"],
    uncertainty_notes: ["Use artwork metadata; avoid private intent."],
    provenance: [P.moma("collection/works/81435")],
    transfer_scope: ["conceptual_art", "reference", "art_language"]
  })
];

const closureWorks = [
  workCard({
    id: "work.norwegian_wood",
    names: ["挪威的森林", "Norwegian Wood"],
    domain: "literature.japanese",
    creator_ids: ["person.haruki_murakami"],
    work_type: "novel",
    period: "contemporary_japanese_literature",
    factual_core: "Haruki Murakami novel anchor for memory, youth, loss, and accessible contemporary fiction.",
    themes: ["memory", "youth", "loss"],
    style_axes: ["accessible_prose", "music_reference", "retrospection"],
    related_concepts: ["theme.memory", "theme.youth_memory"],
    provenance: [P.brit("biography/Haruki-Murakami")],
    transfer_scope: ["Japanese_literature", "youth_memory", "representative_work"]
  }),
  workCard({
    id: "work.song.one_night_in_beijing",
    names: ["北京一夜", "One Night in Beijing"],
    domain: "music.taiwan",
    creator_ids: ["person.chen_sheng"],
    work_type: "song",
    period: "taiwan_pop_1990s",
    factual_core: "Song anchor associated with Chen Sheng and cross-style Mandarin popular music memory.",
    themes: ["city", "memory", "Mandarin_pop"],
    style_axes: ["vocal_drama", "city_image"],
    related_concepts: ["theme.memory", "concept.city_street"],
    provenance: [P.official("Britannica:popular music", "https://www.britannica.com/art/popular-music")],
    transfer_scope: ["representative_song", "city_music", "Mandarin_pop"]
  }),
  workCard({
    id: "work.mai_hime",
    names: ["舞姬", "The Dancing Girl"],
    domain: "literature.japanese",
    creator_ids: ["person.mori_ogai"],
    work_type: "short_story",
    period: "meiji_modern_literature",
    factual_core: "Mori Ōgai story anchor for Meiji modernity, selfhood, and cross-cultural conflict.",
    themes: ["Meiji", "selfhood", "cross_cultural_conflict"],
    style_axes: ["confession", "modern_subject"],
    related_concepts: ["theme.freedom_responsibility"],
    provenance: [P.brit("biography/Mori-Ogai")],
    transfer_scope: ["Japanese_modern_literature", "selfhood", "representative_work"]
  }),
  workCard({
    id: "work.family_ba_jin",
    names: ["家", "Family"],
    domain: "literature.chinese_modern",
    creator_ids: ["person.ba_jin"],
    work_type: "novel",
    period: "modern_chinese_literature",
    factual_core: "Ba Jin novel anchor for family order, youth, and modern social critique.",
    themes: ["family", "youth", "social_critique"],
    style_axes: ["family_structure", "generational_conflict"],
    related_concepts: ["theme.youth_memory", "theme.freedom_responsibility"],
    provenance: [P.brit("biography/Ba-Jin")],
    transfer_scope: ["modern_chinese_literature", "family_conflict", "representative_work"]
  }),
  workCard({
    id: "work.tokyo_story",
    names: ["东京物语", "Tokyo Story"],
    domain: "film.japanese",
    creator_ids: ["person.ozu_yasujiro"],
    work_type: "film",
    period: "postwar_japanese_cinema",
    factual_core: "Ozu film anchor for family time, distance, aging, and ordinary life.",
    themes: ["family", "aging", "ordinary_life"],
    style_axes: ["restraint", "domestic_space", "time"],
    related_concepts: ["concept.restraint", "theme.memory"],
    provenance: [P.criterion("films/284-tokyo-story")],
    transfer_scope: ["Japanese_film", "family_memory", "slowness_questions"]
  }),
  workCard({
    id: "work.late_spring",
    names: ["晚春", "Late Spring"],
    domain: "film.japanese",
    creator_ids: ["person.ozu_yasujiro"],
    work_type: "film",
    period: "postwar_japanese_cinema",
    factual_core: "Ozu film anchor for family relation, seasonal title, and restrained change.",
    themes: ["family", "season", "change"],
    style_axes: ["restraint", "domestic_time", "ellipsis"],
    related_concepts: ["concept.restraint", "concept.seasonality"],
    provenance: [P.criterion("films/298-late-spring")],
    transfer_scope: ["Japanese_film", "seasonality", "family_relation"]
  }),
  workCard({
    id: "work.a_city_of_sadness",
    names: ["悲情城市", "A City of Sadness"],
    domain: "film.taiwan",
    creator_ids: ["person.hou_hsiao_hsien"],
    work_type: "film",
    period: "Taiwan_New_Cinema",
    factual_core: "Hou Hsiao-hsien film anchor for Taiwan history, family, memory, and public silence.",
    themes: ["history", "memory", "family"],
    style_axes: ["long_take", "historical_distance", "everyday_detail"],
    related_concepts: ["theme.memory", "movement.taiwan_new_cinema"],
    provenance: [P.official("Britannica:Hou Hsiao-hsien", "https://www.britannica.com/biography/Hou-Hsiao-hsien")],
    transfer_scope: ["Taiwan_cinema", "history_film", "memory"]
  }),
  workCard({
    id: "work.yi_yi",
    names: ["一一", "Yi Yi"],
    domain: "film.taiwan",
    creator_ids: ["person.edward_yang"],
    work_type: "film",
    period: "Taiwan_New_Cinema",
    factual_core: "Edward Yang film anchor for family, city, perception, and modern life.",
    themes: ["family", "city", "perception"],
    style_axes: ["ensemble", "urban_observation", "duration"],
    related_concepts: ["concept.city_street", "theme.memory"],
    provenance: [P.criterion("films/781-yi-yi")],
    transfer_scope: ["Taiwan_cinema", "city_life", "family_structure"]
  }),
  workCard({
    id: "work.to_the_lighthouse",
    names: ["到灯塔去", "To the Lighthouse"],
    domain: "literature.western_modern",
    creator_ids: ["person.virginia_woolf"],
    work_type: "novel",
    period: "modernism",
    factual_core: "Virginia Woolf novel anchor for time, perception, family, and modernist form.",
    themes: ["time", "perception", "family"],
    style_axes: ["interior_time", "narrative_shift"],
    related_concepts: ["concept.time_memory", "concept.narrator_point_of_view"],
    provenance: [P.brit("topic/To-the-Lighthouse")],
    transfer_scope: ["modernism", "time_memory", "narration"]
  }),
  workCard({
    id: "work.mrs_dalloway",
    names: ["达洛维夫人", "Mrs Dalloway"],
    domain: "literature.western_modern",
    creator_ids: ["person.virginia_woolf"],
    work_type: "novel",
    period: "modernism",
    factual_core: "Virginia Woolf novel anchor for one-day structure, consciousness, city, and memory.",
    themes: ["consciousness", "city", "memory"],
    style_axes: ["interior_time", "urban_walk"],
    related_concepts: ["concept.time_memory", "concept.city_street"],
    provenance: [P.brit("topic/Mrs-Dalloway-novel-by-Woolf")],
    transfer_scope: ["modernism", "city_literature", "memory"]
  }),
  workCard({
    id: "work.course_in_general_linguistics",
    names: ["普通语言学教程", "Course in General Linguistics"],
    domain: "language",
    creator_ids: ["person.ferdinand_de_saussure"],
    work_type: "theory_text",
    period: "early_20th_century",
    factual_core: "Saussure-linked linguistics text anchor for sign, structure, and difference.",
    themes: ["sign", "language_structure", "difference"],
    style_axes: ["conceptual_distinction", "system_relation"],
    related_concepts: ["concept.reference", "theme.naming"],
    provenance: [P.brit("biography/Ferdinand-de-Saussure")],
    transfer_scope: ["language", "reference", "translation"]
  }),
  workCard({
    id: "work.philosophical_investigations",
    names: ["哲学研究", "Philosophical Investigations"],
    domain: "philosophy",
    creator_ids: ["person.ludwig_wittgenstein"],
    work_type: "philosophy_text",
    period: "20th_century",
    factual_core: "Wittgenstein text anchor for language use, meaning, and ordinary examples.",
    themes: ["language_use", "meaning", "example"],
    style_axes: ["ordinary_language", "fragmentary_inquiry"],
    related_concepts: ["concept.reference", "theme.naming"],
    provenance: [P.sep("wittgenstein")],
    transfer_scope: ["philosophy", "language", "meaning_questions"]
  }),
  workCard({
    id: "work.eames_lounge_chair",
    names: ["Eames Lounge Chair", "伊姆斯休闲椅"],
    domain: "design_history",
    creator_ids: ["person.charles_eames", "person.ray_eames"],
    work_type: "design_object",
    period: "modern_design",
    factual_core: "Charles and Ray Eames design anchor for materials, comfort, production, and modern domestic design.",
    themes: ["materials", "comfort", "industrial_design"],
    style_axes: ["molded_plywood", "leather", "use"],
    related_concepts: ["concept.form_material_institution"],
    provenance: [P.official("Eames Office:Charles and Ray", "https://www.eamesoffice.com/charles-and-ray/")],
    transfer_scope: ["design", "material_culture", "authorship"]
  }),
  workCard({
    id: "work.braun_skj4",
    names: ["Braun SK4", "SK4"],
    domain: "design_history",
    creator_ids: ["person.dieter_rams"],
    work_type: "design_object",
    period: "modern_design",
    factual_core: "Braun design anchor for clarity, function, material restraint, and modern product form.",
    themes: ["industrial_design", "clarity", "function"],
    style_axes: ["transparent_lid", "restraint", "usability"],
    related_concepts: ["concept.form_material_institution", "concept.restraint"],
    provenance: [P.official("Vitsoe:Dieter Rams", "https://www.vitsoe.com/us/about/dieter-rams")],
    transfer_scope: ["design", "function", "material_form"]
  })
];

const relations = [
  ["relation.lu_xun_diary_of_a_madman", "person_to_work", ["person.lu_xun"], ["work.diary_of_a_madman"], ["vernacular", "critique"], ["story_form"], ["is exemplified by", "helps explain"]],
  ["relation.lu_xun_true_story_ah_q", "person_to_work", ["person.lu_xun"], ["work.true_story_ah_q"], ["satire", "subject"], ["narrative_distance"], ["is exemplified by", "frames"]],
  ["relation.eileen_chang_half_lifelong_romance", "person_to_work", ["person.eileen_chang"], ["work.half_a_lifelong_romance"], ["urban_relation", "time"], ["cool_detail"], ["is exemplified by", "helps explain"]],
  ["relation.eileen_chang_golden_cangue", "person_to_work", ["person.eileen_chang"], ["work.the_golden_cangue"], ["gender", "family_pressure"], ["bleakness"], ["is exemplified by", "helps explain"]],
  ["relation.teresa_teng_moon_represents_my_heart", "person_to_work", ["person.teresa_teng"], ["work.moon_represents_my_heart"], ["Mandarin_pop", "memory"], ["vocal_style"], ["is exemplified by", "frames"]],
  ["relation.cui_jian_nothing_to_my_name", "person_to_work", ["person.cui_jian"], ["work.nothing_to_my_name"], ["rock", "public_voice"], ["generation"], ["is exemplified by", "frames"]],
  ["relation.ozu_tokyo_story", "person_to_work", ["person.ozu_yasujiro"], ["work.tokyo_story"], ["family", "time"], ["restraint"], ["is exemplified by", "helps explain"]],
  ["relation.ozu_late_spring", "person_to_work", ["person.ozu_yasujiro"], ["work.late_spring"], ["family", "season"], ["restraint"], ["is exemplified by", "helps explain"]],
  ["relation.kurosawa_rashomon", "person_to_work", ["person.akira_kurosawa"], ["work.rashomon_kurosawa"], ["testimony", "truth_claim"], ["perspective"], ["is exemplified by", "frames"]],
  ["relation.kurosawa_seven_samurai", "person_to_work", ["person.akira_kurosawa"], ["work.seven_samurai"], ["group_action", "ethics"], ["movement"], ["is exemplified by", "frames"]],
  ["relation.edward_yang_brighter_summer_day", "person_to_work", ["person.edward_yang"], ["work.a_brighter_summer_day"], ["youth", "history"], ["urban_pressure"], ["is exemplified by", "frames"]],
  ["relation.wong_kar_wai_in_the_mood", "person_to_work", ["person.wong_kar_wai"], ["work.in_the_mood_for_love"], ["longing", "time"], ["restraint"], ["is exemplified by", "helps explain"]],
  ["relation.ann_hui_boat_people", "person_to_work", ["person.ann_hui"], ["work.boat_people"], ["history", "migration"], ["political_context"], ["is exemplified by", "frames"]],
  ["relation.jia_zhangke_still_life", "person_to_work", ["person.jia_zhangke"], ["work.still_life_jia"], ["modernization_loss", "place"], ["displacement"], ["is exemplified by", "helps explain"]],
  ["relation.koreeda_still_walking", "person_to_work", ["person.koreeda_hirokazu"], ["work.still_walking"], ["family", "memory"], ["restraint"], ["is exemplified by", "helps explain"]],
  ["relation.hou_taiwan_new_cinema", "person_to_movement", ["person.hou_hsiao_hsien"], ["movement.taiwan_new_cinema"], ["Taiwan_cinema", "history"], ["long_take"], ["is often read through", "frames"]],
  ["relation.gropius_bauhaus", "person_to_movement", ["person.walter_gropius"], ["movement.bauhaus_design"], ["school", "design"], ["institution"], ["frames", "is often read through"]],
  ["relation.rashomon_testimony_truth", "work_to_concept", ["work.rashomon_kurosawa"], ["concept.testimony", "concept.truth_claim"], ["perspective", "testimony"], ["truth_claim"], ["helps explain", "is often read through"]],
  ["relation.in_the_mood_restraint_time", "work_to_concept", ["work.in_the_mood_for_love"], ["concept.restraint", "concept.longing", "concept.time_memory"], ["longing", "time"], ["withholding"], ["helps explain", "overlaps with"]],
  ["relation.camera_lucida_memory_punctum", "work_to_concept", ["work.camera_lucida"], ["theme.memory", "concept.punctum"], ["photography", "memory"], ["viewer_specificity"], ["helps explain", "frames"]],
  ["relation.fountain_readymade_institution", "work_to_concept", ["work.fountain"], ["concept.readymade", "concept.authorship", "theme.institution"], ["selection", "institution"], ["object_status"], ["helps explain", "frames"]],
  ["relation.one_and_three_chairs_reference", "work_to_concept", ["work.one_and_three_chairs"], ["concept.object_image_language", "concept.reference"], ["object", "image", "language"], ["representation"], ["helps explain", "frames"]],
  ["relation.death_life_street_public_space", "work_to_concept", ["work.death_and_life_great_american_cities"], ["concept.city_street", "concept.public_space", "concept.diversity_city"], ["street", "public_space"], ["planning"], ["helps explain", "frames"]],
  ["relation.wabi_sabi_mono_no_aware", "concept_to_concept", ["concept.wabi_sabi"], ["concept.mono_no_aware"], ["impermanence", "aesthetic_attention"], ["object_surface", "emotional_pathos"], ["overlaps with", "differs from"]],
  ["relation.wabi_sabi_minimalism_negative", "concept_to_concept", ["concept.wabi_sabi"], ["movement.minimalism"], ["restraint"], ["cultural_frame", "material_history"], ["differs from", "contrasts with"]],
  ["relation.naming_reference", "concept_to_concept", ["theme.naming"], ["concept.reference"], ["name", "referent"], ["meaning_scope"], ["helps explain", "constrains"]],
  ["relation.memory_narration", "concept_to_concept", ["theme.memory"], ["concept.narrative_memory"], ["memory", "story"], ["archive", "experience"], ["overlaps with", "helps explain"]],
  ["relation.mono_no_aware_youth_memory", "concept_to_concept", ["concept.mono_no_aware"], ["theme.youth_memory"], ["retrospection", "loss"], ["cultural_context"], ["echoes", "differs from"]],
  ["relation.rule_application_precedent", "concept_to_concept", ["concept.rule_application_precedent"], ["theme.institution"], ["rule", "institution"], ["jurisdiction"], ["constrains", "helps explain"]],
  ["relation.form_material_institution", "concept_to_concept", ["concept.form_material_institution"], ["theme.institution"], ["form", "material", "institution"], ["style_only"], ["frames", "constrains"]],
  ["relation.ozu_kurosawa_contrast", "contrast_foil", ["person.ozu_yasujiro"], ["person.akira_kurosawa"], ["Japanese_cinema"], ["tempo", "movement", "conflict_form"], ["contrasts with", "differs from"]],
  ["relation.hou_edward_yang_contrast", "contrast_foil", ["person.hou_hsiao_hsien"], ["person.edward_yang"], ["Taiwan_cinema", "history"], ["urban_structure", "duration"], ["contrasts with", "differs from"]],
  ["relation.wong_hou_contrast", "contrast_foil", ["person.wong_kar_wai"], ["person.hou_hsiao_hsien"], ["time", "memory"], ["urban_mood", "historical_space"], ["contrasts with", "echoes"]],
  ["relation.lu_xun_eileen_chang_contrast", "contrast_foil", ["person.lu_xun"], ["person.eileen_chang"], ["modern_chinese_literature"], ["satire", "urban_relation", "historical_pressure"], ["contrasts with", "differs from"]]
].map(([id, relation_type, source_ids, target_ids, shared_axes, contrast_axes, licensed_verbs]) => relationCard({
  id,
  names: [id.replace(/^relation\./, "").replaceAll("_", " ")],
  domain: "relation_graph",
  relation_type,
  source_ids,
  target_ids,
  shared_axes,
  contrast_axes,
  licensed_verbs,
  example_ids: [],
  constraints: ["no identity collapse", "no causal claim without source", "no stronger verb than licensed"],
  negative_moves: ["do_not_claim_same_as", "do_not_claim_direct_causation", "do_not_explain_all_of_target"],
  provenance: [P.official("R24 curated public-source synthesis", "https://www.britannica.com/")],
  transfer_scope: ["comparison", "concept_followup", "topic_reentry"]
}));

function writeJsonl(file, rows) {
  fs.writeFileSync(file, `${rows.map((row) => JSON.stringify(row)).join("\n")}\n`);
}

function main() {
  const ids = existingIds();
  const skipped = [];
  const keepNew = (row) => {
    if (ids.has(row.id)) {
      skipped.push(row.id);
      return false;
    }
    ids.add(row.id);
    return true;
  };
  const stage0Rows = stage0.filter(keepNew);
  const stage1Rows = [
    ...stage1Concepts,
    ...closureConcepts,
    ...persons,
    ...closurePersons,
    ...works,
    ...closureWorks,
    ...relations
  ].filter(keepNew);
  writeJsonl(STAGE0_FILE, stage0Rows);
  writeJsonl(STAGE1A_FILE, stage1Rows);
  const summary = {
    stage0_file: path.relative(ROOT, STAGE0_FILE),
    stage1a_file: path.relative(ROOT, STAGE1A_FILE),
    stage0_cards: stage0Rows.length,
    stage1a_cards: stage1Rows.length,
    skipped_existing_ids: skipped
  };
  console.log(JSON.stringify(summary, null, 2));
}

main();
