import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const CARD_DIR = path.join(ROOT, "data", "culture_cards");
const OUT = path.join(ROOT, "web", "culture_cards.generated.js");

function readJsonl(file) {
  const text = fs.readFileSync(file, "utf8");
  return text
    .split(/\r?\n/)
    .filter((line) => line.trim())
    .map((line, index) => {
      try {
        return JSON.parse(line);
      } catch (error) {
        throw new Error(`${path.relative(ROOT, file)}:${index + 1} ${error.message}`);
      }
    });
}

function main() {
  const files = fs
    .readdirSync(CARD_DIR)
    .filter((name) => name.endsWith(".jsonl"))
    .sort();
  const cards = files
    .flatMap((file) => readJsonl(path.join(CARD_DIR, file)))
    .filter((card) => card.needs_review !== true && card.confidence >= 0.75 && card.visibility === "public" && card.approved_for_public_runtime === true);
  const ids = new Set();
  for (const card of cards) {
    if (ids.has(card.id)) throw new Error(`duplicate culture card id: ${card.id}`);
    ids.add(card.id);
  }

  const header = [
    "// Generated by scripts/build_culture_cards.mjs.",
    "// Do not edit by hand. Source cards live in data/culture_cards/*.jsonl.",
    "// This module contains abstract public-safe culture cards, not raw source text.",
    ""
  ].join("\n");
  const body = `export const CULTURE_CARDS = ${JSON.stringify(cards, null, 2)};\n`;
  fs.writeFileSync(OUT, `${header}${body}`);
  console.log(`generated ${path.relative(ROOT, OUT)} (${cards.length} cards from ${files.length} files)`);
}

main();
