#!/usr/bin/env node
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const MODEL = resolve(ROOT, "artifacts/training_os/controlled_gate_model.json");
const EVAL_REPORT = resolve(ROOT, "artifacts/training_os/controlled_gate_eval_report.json");
const EXPORT_REPORT = resolve(ROOT, "artifacts/training_os/controlled_gate_export_report.json");
const WEB_MODEL = resolve(ROOT, "web/controlled_gate_model.generated.js");

async function main() {
  if (!existsSync(MODEL) || !existsSync(EVAL_REPORT)) {
    throw new Error("Controlled gate model/eval report missing.");
  }
  const evalReport = JSON.parse(await readFile(EVAL_REPORT, "utf8"));
  const model = JSON.parse(await readFile(MODEL, "utf8"));
  const exported = evalReport.ready_for_runtime === true;
  const report = {
    ok: true,
    exported,
    target: exported ? WEB_MODEL.replace(`${ROOT}/`, "") : "",
    reason: exported ? "metrics passed and cycle count is sufficient" : "metrics or cycle count below runtime export threshold",
    cycle: model.cycle,
    ready_for_runtime: evalReport.ready_for_runtime
  };
  if (exported) {
    const header = [
      "// Generated by scripts/export_controlled_gate_model.mjs.",
      "// Controlled gate labels only; this is not a final-answer generator.",
      ""
    ].join("\n");
    await writeFile(WEB_MODEL, `${header}export const CONTROLLED_GATE_MODEL = ${JSON.stringify(model)};\n`, "utf8");
  }
  await mkdir(dirname(EXPORT_REPORT), { recursive: true });
  await writeFile(EXPORT_REPORT, JSON.stringify(report, null, 2), "utf8");
  console.log(JSON.stringify(report, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exit(2);
});
