#!/usr/bin/env node
import { readJson, writeJson, writeText } from "./r26a_project_utils.mjs";
import { R26D_PACK_ID } from "./r26d_question_pack_utils.mjs";

async function main() {
  const audit = await readJson("artifacts/training_os/user_answer_intake/r26d/r26d_first50_audit.json");
  const generation = await readJson("artifacts/training_os/user_answer_intake/r26d/r26d_first50_generation_report.json");
  const validation = await readJson("artifacts/training_os/user_answer_intake/r26d/r26d_first50_candidate_validation.json");
  const guard = await readJson("artifacts/training_os/user_answer_intake/r26d/r26d_question_pack_exclusion_guard.json");
  const trainingStatus = await readJson("training/current/training_status.json").catch(() => null);
  const report = {
    ok: Boolean(audit.ok && validation.ok && guard.ok),
    phase: "R26D",
    pack_id: R26D_PACK_ID,
    total_rows_parsed: audit.total_rows_parsed,
    candidate_rows_1_to_50_answered: audit.first50_answered_count,
    candidate_count: generation.candidate_count,
    excluded_rows_51_to_100_status: audit.rows_51_100_exclusion_status,
    raw_csv_committed: false,
    rows_51_100_in_candidates: validation.rows_51_100_candidates,
    rows_51_100_in_training_corpus: guard.rows_51_100_in_training_corpus,
    rows_51_100_in_tokenizer_configs: 0,
    rows_51_100_in_teacher_probe_configs: 0,
    allowed_next_action: [
      "review first-50 candidates",
      "approve R26E promotion of selected reviewed rows only if desired",
      "do not train now"
    ],
    training_status: trainingStatus,
    training_ran: false,
    tokenizer_dry_run_ran: false,
    corpus_promotion_ran: false,
    phase_4_scaled_training_approved: false
  };
  await writeJson("artifacts/training_os/user_answer_intake/r26d/r26d_question_pack_status.json", report);
  const statusMarkdown = `# R26D First-50 User Answer Intake

R26D parsed the approved ignored answer pack at \`private_sources/question_packs/another_brain_question_pack_001_answered.csv\` and converted only question IDs 1-50 into ignored answer-as-user candidate artifacts.

Rows 51-100 remain hard-excluded because they are project-meta, training-meta, status, or engineering prompts rather than real answer-as-user dialogue material. They were not used for candidate rows, preference pairs, repair pairs, teacher probes, tokenizer text, eval-derived training seeds, long-horizon rows, corpus generation, or corpus promotion.

## Status

- pack_id: ${report.pack_id}
- total rows parsed: ${report.total_rows_parsed}
- rows 1-50 answered: ${report.candidate_rows_1_to_50_answered}
- generated candidates: ${report.candidate_count}
- rows 51-100 status: ${report.excluded_rows_51_to_100_status}
- rows 51-100 in candidates: ${report.rows_51_100_in_candidates}
- rows 51-100 in training corpus: ${report.rows_51_100_in_training_corpus}
- raw CSV committed: false
- training ran: false
- tokenizer dry-run ran: false
- corpus promotion ran: false

The candidate JSONL and review pack are ignored artifacts. R26E would require fresh approval before any selected reviewed candidates can be promoted into tracked corpus files.
`;
  await writeText("docs/R26D_FIRST50_USER_ANSWER_INTAKE.md", statusMarkdown);
  await writeText("docs/R26D_QUESTION_PACK_STATUS.md", statusMarkdown);
  await writeText(
    "docs/R26D_QUESTION_PACK_EXCLUSION_GUARD.md",
    `# R26D Question Pack Exclusion Guard

The R26D guard enforces the R26C/R26D boundary for \`${R26D_PACK_ID}\`.

## Hard Boundary

- IDs 1-50: candidate_review_only
- IDs 51-100: excluded_from_training

The guard fails if rows 51-100 appear in R26D candidates, active training corpus files, current corpus manifests, tokenizer configs, teacher probe configs, future corpus expansion plans, or staged raw CSV/XLSX files.

Current result: ${guard.ok ? "pass" : "fail"}.
`
  );
  await writeText(
    "docs/R26D_NEXT_QUESTION_PACK_BOUNDARY.md",
    `# R26D Next Question Pack Boundary

Replacement questions for rows 51-100 should be generated by the model-side planning assistant, not by Codex, because Codex tends to drift toward engineering and project-meta prompts.

Codex's role is intake, validation, slicing, policy enforcement, and gate reporting. The next replacement question pack should focus on friend-facing answer-as-user situations: strange abstract questions, unsupported challenges, sincere shallow questions, intrusive questions, relation-sensitive questions, evidence-bearing corrections, memory uncertainty, refusal boundaries, and compressed judgments.

No replacement questions are generated in R26D.
`
  );
  console.log(JSON.stringify(report, null, 2));
  if (!report.ok) process.exit(2);
}

main().catch((error) => {
  console.error(error);
  process.exit(2);
});
